#!/bin/sh
set -e

TEMP_DIR=${TEMP:-"/tmp"}
TARGET_DIR="${TEMP_DIR}/gh"
TARGET_CONFIG="${TARGET_DIR}/hosts.yml"
SOURCE_CONFIG="${HOME}/.config/gh/hosts.yml"

mkdir -p "${TARGET_DIR}"

if [ -f "${SOURCE_CONFIG}" ]; then
    cp "${SOURCE_CONFIG}" "${TARGET_CONFIG}"
    chmod 600 "${TARGET_CONFIG}"
fi
