#!/bin/sh
set -e

TEMP_DIR=${TEMP:-"/tmp"}
TARGET_DIR="${TEMP_DIR}/cursor"
TARGET_AUTH="${TARGET_DIR}/auth.json"

SOURCE_AUTH="${HOME}/.config/cursor/auth.json"

mkdir -p "${TARGET_DIR}"

if [ -f "${SOURCE_AUTH}" ]; then
    cp "${SOURCE_AUTH}" "${TARGET_AUTH}"
    chmod 600 "${TARGET_AUTH}"
fi
